---
- hosts: all
  tasks:
    - name: creating multiple files at a time
      file:
        path: /opt/Cloudgen/{{item}}
        state: touch
      with_items:
      - sum.java
      - hell.java
      - cloudgen.txt
      - ravindra.txt
